resources:
- name: helloworld
  type: git
  source:
    uri: https://github.com/goehringa/helloworld
    branch: master

jobs:
- name: test-app
  plan:
  - get: helloworld
    trigger: true
  - task: tests
    file: helloworld/build.yml
