resource_types:
- name: github-status
  type: docker-image
  source:
    repository: dpb587/github-status-resource
    tag: master

resources:
- name: helloworld
  type: git
  source:
    uri: https://github.com/goehringa/helloworld
    branch: master

- name: helloworld-docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-hub-image-helloworld}}

- name: repo
  type: git
  source:
    uri: https://github.com/goehringa/helloworld
    branch: master

- name: repo-status
  type: github-status
  source:
    repository: goehringa/helloworld
    access_token: {{github-token}}

jobs:
- name: test-app
  serial: true
  build_logs_to_retain: 5
  plan:
  - get: helloworld
  - get: repo
    trigger: true
  - put: repo-status
    params: {state: pending, commit: repo}
  - task: tests
    file: helloworld/build.yml
    on_failure:
      put: repo-status
      params: {state: failure, commit: repo}
  - put: helloworld-docker-image
    params:
      build: helloworld/docker
  - task: container-tests
    file: helloworld/integration_tests.yml
    on_failure:
      put: repo-status
      params: {state: failure, commit: repo}

